"""Bake js/schedule_data.js — who actually teaches each course, per term.

Source (LOCAL, written by sources/class_schedule.py):
    data/class_schedule.json

Output: js/schedule_data.js defining a single `SCHEDULE` global.

Shape is deliberately compact: instructor names are interned once into a flat
array and each course holds indices into it. Names repeat heavily (a professor
teaches many sections across many courses), so this is the difference between
~160 KB and roughly half a megabyte of duplicated strings.

    SCHEDULE = {
      scraped: "2026-07-29",
      terms:   [{code:"20271", label:"Winter 2027"}, ...],   // newest first
      names:   ["Ken Rodham", "Lee Jensen", ...],
      byTerm:  { "20271": { "C S 240": [0, 1] }, ... }
    }

app.js resolves a course to the NEWEST term that lists it and always shows the
term alongside the names — "who teaches this" is only meaningful attached to a
semester, and a stale name presented bare is worse than no name at all.
"""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).parent
SRC = HERE / "data" / "class_schedule.json"
OUT = HERE.parent / "js" / "schedule_data.js"


def main() -> int:
    if not SRC.exists():
        print(f"generate_schedule: {SRC} missing — run sources/class_schedule.py first")
        return 1
    d = json.loads(SRC.read_text(encoding="utf-8"))
    payload = {
        "scraped": d.get("scraped"),
        # {termCode: {cart, reg}} — when the registration cart opens and when
        # priority registration begins, from the registrar's own table. The UI
        # uses these to date its "not open yet" notices.
        "regDates": d.get("regDates", {}),
        "terms": d.get("terms", []),
        "historyTerms": d.get("historyTerms", []),
        "names": d.get("instructors", []),
        "byTerm": d.get("byTerm", {}),
        # [[nameIdx, termsTaught], ...] for courses NO live term lists — the
        # "who usually teaches this" fallback for a course four years out.
        "historic": d.get("historic", {}),
    }
    body = json.dumps(payload, separators=(",", ":"), ensure_ascii=False)
    js = (
        "/* AUTO-GENERATED by scraper/generate_schedule.py — do not edit.\n"
        "   Who teaches each course, from BYU's public class schedule\n"
        "   (commtech.byu.edu/noauth/classSchedule). Names are interned into\n"
        "   `names`; each course holds indices into it. See the generator for\n"
        "   why the term label must always be shown with the names. */\n"
        f"const SCHEDULE = {body};\n"
    )
    OUT.write_text(js, encoding="utf-8")
    n = sum(len(v) for v in payload["byTerm"].values())
    print(f"wrote {OUT} ({OUT.stat().st_size/1024:.0f} KB) — "
          f"{len(payload['names'])} instructors, {n} course-term rows, "
          f"terms: {[t['label'] for t in payload['terms']]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
