/*
 * data.js — BYU Scholarship Matcher dataset
 * -------------------------------------------------------------
 * Majors are organized by BYU's actual colleges so the matcher can
 * map "your major -> your college's scholarships." Scholarship
 * details come from official BYU pages (see URLs). Always verify
 * amounts + exact deadlines on the linked official page.
 *
 * Sources:
 *   Colleges & majors ..... https://www.byu.edu/colleges-and-departments
 *   Financial Aid ......... https://enrollment.byu.edu/financial-aid/scholarships
 *   College/Dept .......... https://enrollment.byu.edu/financial-aid/byu-college-departmental-scholarships
 *   Marriott .............. https://marriott.byu.edu/financialaid/scholarships/
 *   Wheatley .............. https://wheatley.byu.edu/student-scholars
 *   Kennedy Center ........ https://kennedy.byu.edu/scholarships
 * -------------------------------------------------------------
 */

// BYU colleges (key -> display label). "undeclared" is a catch-all.
const COLLEGES = {
  marriott: "Marriott School of Business",
  cpms: "Computing, Mathematical & Physical Sciences",
  engineering: "Ira A. Fulton College of Engineering",
  education: "McKay School of Education",
  fhss: "Family, Home & Social Sciences",
  finearts: "Fine Arts & Communications",
  humanities: "College of Humanities",
  lifesci: "College of Life Sciences",
  nursing: "College of Nursing",
  undeclared: "Undeclared / Other",
};

// Every major carries the college key that drives scholarship matching.
const MAJORS = [
  { value: "undecided", label: "Undecided / Exploring", college: "undeclared" },

  // Marriott School of Business
  { value: "accounting", label: "Accounting", college: "marriott" },
  { value: "finance", label: "Finance", college: "marriott" },
  { value: "information-systems", label: "Information Systems", college: "marriott" },
  { value: "marketing", label: "Marketing", college: "marriott" },
  { value: "entrepreneurship", label: "Entrepreneurship", college: "marriott" },
  { value: "supply-chain", label: "Global Supply Chain Management", college: "marriott" },
  { value: "human-resources", label: "Human Resource Management", college: "marriott" },
  { value: "experience-design", label: "Experience Design & Management", college: "marriott" },
  { value: "strategy", label: "Strategic Management", college: "marriott" },

  // Computing, Mathematical & Physical Sciences
  { value: "computer-science", label: "Computer Science", college: "cpms" },
  { value: "chemistry", label: "Chemistry", college: "cpms" },
  { value: "biochemistry", label: "Biochemistry", college: "cpms" },
  { value: "geology", label: "Geology", college: "cpms" },
  { value: "mathematics", label: "Mathematics", college: "cpms" },
  { value: "applied-math", label: "Applied & Computational Mathematics", college: "cpms" },
  { value: "math-education", label: "Mathematics Education", college: "cpms" },
  { value: "physics", label: "Physics & Astronomy", college: "cpms" },
  { value: "statistics", label: "Statistics", college: "cpms" },
  { value: "data-science", label: "Data Science", college: "cpms" },

  // Ira A. Fulton College of Engineering
  { value: "chemical-engineering", label: "Chemical Engineering", college: "engineering" },
  { value: "civil-engineering", label: "Civil Engineering", college: "engineering" },
  { value: "construction-management", label: "Construction & Facilities Management", college: "engineering" },
  { value: "electrical-engineering", label: "Electrical Engineering", college: "engineering" },
  { value: "computer-engineering", label: "Computer Engineering", college: "engineering" },
  { value: "mechanical-engineering", label: "Mechanical Engineering", college: "engineering" },
  { value: "manufacturing-engineering", label: "Manufacturing Engineering", college: "engineering" },
  { value: "software-engineering", label: "Software Engineering", college: "engineering" },
  { value: "information-technology", label: "Information Technology", college: "engineering" },
  { value: "cybersecurity", label: "Cybersecurity", college: "engineering" },
  { value: "tech-engineering-studies", label: "Technology & Engineering Studies", college: "engineering" },

  // McKay School of Education
  { value: "elementary-education", label: "Elementary Education", college: "education" },
  { value: "early-childhood", label: "Early Childhood Education", college: "education" },
  { value: "special-education", label: "Special Education", college: "education" },
  { value: "communication-disorders", label: "Communication Disorders", college: "education" },

  // Family, Home & Social Sciences
  { value: "economics", label: "Economics", college: "fhss" },
  { value: "anthropology", label: "Anthropology", college: "fhss" },
  { value: "family-life", label: "Family Life / Human Development", college: "fhss" },
  { value: "geography", label: "Geography", college: "fhss" },
  { value: "geospatial", label: "Geospatial Intelligence", college: "fhss" },
  { value: "history", label: "History", college: "fhss" },
  { value: "political-science", label: "Political Science", college: "fhss" },
  { value: "psychology", label: "Psychology", college: "fhss" },
  { value: "social-work", label: "Social Work", college: "fhss" },
  { value: "sociology", label: "Sociology", college: "fhss" },

  // Fine Arts & Communications
  { value: "communications", label: "Communications (Journalism / PR / Ad)", college: "finearts" },
  { value: "studio-art", label: "Studio Arts", college: "finearts" },
  { value: "art-history", label: "Art History & Curatorial Studies", college: "finearts" },
  { value: "art-education", label: "Art Education", college: "finearts" },
  { value: "animation", label: "Animation", college: "finearts" },
  { value: "graphic-design", label: "Graphic Design", college: "finearts" },
  { value: "illustration", label: "Illustration", college: "finearts" },
  { value: "photography", label: "Photography", college: "finearts" },
  { value: "industrial-design", label: "Industrial Design", college: "finearts" },
  { value: "dance", label: "Dance", college: "finearts" },
  { value: "music", label: "Music", college: "finearts" },
  { value: "music-education", label: "Music Education", college: "finearts" },
  { value: "commercial-music", label: "Commercial Music", college: "finearts" },
  { value: "media-arts", label: "Media Arts Studies (Film)", college: "finearts" },
  { value: "theatre", label: "Theatre Arts", college: "finearts" },

  // College of Humanities
  { value: "english", label: "English", college: "humanities" },
  { value: "english-language", label: "English Language / Editing & Publishing", college: "humanities" },
  { value: "linguistics", label: "Linguistics", college: "humanities" },
  { value: "philosophy", label: "Philosophy", college: "humanities" },
  { value: "french", label: "French Studies", college: "humanities" },
  { value: "italian", label: "Italian Studies", college: "humanities" },
  { value: "german", label: "German Studies", college: "humanities" },
  { value: "russian", label: "Russian", college: "humanities" },
  { value: "spanish", label: "Spanish", college: "humanities" },
  { value: "portuguese", label: "Portuguese", college: "humanities" },
  { value: "chinese", label: "Chinese", college: "humanities" },
  { value: "japanese", label: "Japanese", college: "humanities" },
  { value: "korean", label: "Korean", college: "humanities" },
  { value: "asian-studies", label: "Asian Studies", college: "humanities" },
  { value: "ancient-near-eastern", label: "Ancient Near Eastern Studies", college: "humanities" },
  { value: "classics", label: "Classical Studies (Greek / Latin)", college: "humanities" },
  { value: "comparative-lit", label: "Comparative Literature", college: "humanities" },
  { value: "translation", label: "Translation & Localization", college: "humanities" },
  { value: "american-studies", label: "American Studies", college: "humanities" },

  // College of Life Sciences
  { value: "biology", label: "Biology", college: "lifesci" },
  { value: "biology-education", label: "Biology Education", college: "lifesci" },
  { value: "physiology", label: "Physiology & Developmental Biology", college: "lifesci" },
  { value: "exercise-science", label: "Exercise & Wellness / Exercise Science", college: "lifesci" },
  { value: "athletic-training", label: "Athletic Training", college: "lifesci" },
  { value: "microbiology", label: "Microbiology", college: "lifesci" },
  { value: "molecular-biology", label: "Molecular Biology", college: "lifesci" },
  { value: "biotechnology", label: "Biotechnology", college: "lifesci" },
  { value: "neuroscience", label: "Neuroscience", college: "lifesci" },
  { value: "nutrition", label: "Nutritional Science", college: "lifesci" },
  { value: "dietetics", label: "Dietetics", college: "lifesci" },
  { value: "food-science", label: "Food Science", college: "lifesci" },
  { value: "plant-science", label: "Plant & Wildlife Sciences", college: "lifesci" },
  { value: "wildlife", label: "Wildlife & Wildlands Conservation", college: "lifesci" },
  { value: "environmental-science", label: "Environmental Science", college: "lifesci" },
  { value: "public-health", label: "Public Health", college: "lifesci" },
  { value: "genetics", label: "Genetics, Genomics & Biotechnology", college: "lifesci" },

  // College of Nursing
  { value: "nursing", label: "Nursing", college: "nursing" },

  { value: "other", label: "Other / Not listed", college: "undeclared" },
];

const LEVELS = [
  { value: "incoming-freshman", label: "Incoming freshman" },
  { value: "freshman", label: "Freshman (current)" },
  { value: "sophomore", label: "Sophomore" },
  { value: "junior", label: "Junior" },
  { value: "senior", label: "Senior" },
  { value: "transfer", label: "Transfer student" },
];

const CONTINUING = ["freshman", "sophomore", "junior", "senior", "transfer"];

const SCHOLARSHIPS = [
  /* ---------------- University-wide (Financial Aid Office) ---------------- */
  {
    id: "byu-freshman-merit",
    name: "New Freshman Scholarships (Presidential, Heritage, etc.)",
    provider: "BYU Financial Aid Office",
    group: "University",
    award: "Half to full tuition (award tiers by academic index)",
    minGPA: 3.7,
    levels: ["incoming-freshman"],
    colleges: ["any"],
    needBased: false,
    meritBased: true,
    internationalEligible: true,
    deadline: { month: 12, day: 15 },
    deadlineNote: "Awarded automatically from your admissions application — no separate form.",
    url: "https://enrollment.byu.edu/financial-aid/new-freshman-scholarships",
    requirements: [
      "Considered automatically when you apply for admission.",
      "Ranked on an academic index (high-school GPA + test scores).",
      "Higher index = higher award tier, up to full tuition.",
    ],
  },
  {
    id: "byu-continuing-academic",
    name: "Continuing Student Academic Scholarship",
    provider: "BYU Financial Aid Office",
    group: "University",
    award: "Half to full LDS tuition (GPA cutoff varies yearly)",
    minGPA: 3.7,
    minCredits: 12,
    levels: CONTINUING,
    colleges: ["any"],
    needBased: false,
    meritBased: true,
    internationalEligible: true,
    deadline: { month: 2, day: 1 },
    deadlineNote: "General deadline Feb 1; submit the FAFSA by Jan 20 for need consideration.",
    url: "https://enrollment.byu.edu/financial-aid/former-continuing-student-scholarships",
    requirements: [
      "Complete at least 12 BYU credit hours by the end of fall semester.",
      "Meet the cumulative GPA cutoff (set yearly by college — competitive).",
      "Multi-year awards require maintaining a 3.70 cumulative GPA.",
    ],
  },
  {
    id: "byu-need-based",
    name: "Need-Based Scholarships (incl. Cougar Pell Promise / Elevated)",
    provider: "BYU Financial Aid Office",
    group: "University",
    award: "Half to full LDS tuition (need-based)",
    minGPA: 2.5,
    levels: ["incoming-freshman", ...CONTINUING],
    colleges: ["any"],
    needBased: true,
    meritBased: false,
    internationalEligible: false,
    deadline: { month: 1, day: 20 },
    deadlineNote: "Requires the FAFSA — submit by Jan 20.",
    url: "https://enrollment.byu.edu/financial-aid/former-continuing-student-scholarships",
    requirements: [
      "Submit the FAFSA by January 20.",
      "Demonstrated financial need (Pell-eligible students prioritized).",
      "U.S. citizen or eligible non-citizen (FAFSA requirement).",
    ],
  },
  {
    id: "byu-private-donor",
    name: "Private Donor Scholarships (administered by BYU)",
    provider: "BYU Financial Aid Office",
    group: "University",
    award: "Half or full LDS tuition (varies by donor)",
    minGPA: 3.0,
    levels: CONTINUING,
    colleges: ["any"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    deadline: { month: 2, day: 1 },
    deadlineNote: "Considered with the general Feb 1 scholarship application.",
    url: "https://enrollment.byu.edu/financial-aid/former-continuing-student-scholarships",
    requirements: [
      "Criteria set by the donor — often hometown, high school, or family ties.",
      "Mix of need-based and merit-based funds.",
      "One application covers you for many donor funds automatically.",
    ],
  },
  {
    id: "byu-transfer",
    name: "Transfer Student Scholarships",
    provider: "BYU Financial Aid Office",
    group: "University",
    award: "Varies (merit + need)",
    minGPA: 3.5,
    levels: ["transfer"],
    colleges: ["any"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    deadline: { month: 2, day: 1 },
    deadlineNote: "Complete 12+ BYU credits before you're eligible for FA academic awards.",
    url: "https://enrollment.byu.edu/financial-aid/transfer-students-scholarships",
    requirements: [
      "Transfer at least 12 credits of regular coursework.",
      "Strong transfer GPA (competitive).",
      "Some awards recognize your first semesters at BYU.",
    ],
  },
  {
    id: "byu-international",
    name: "International Student Scholarships",
    provider: "BYU Financial Aid Office",
    group: "University",
    award: "Varies (merit-based)",
    minGPA: 3.5,
    levels: ["incoming-freshman", ...CONTINUING],
    colleges: ["any"],
    needBased: false,
    meritBased: true,
    internationalEligible: true,
    internationalOnly: true,
    deadline: { month: 2, day: 1 },
    deadlineNote: "For international students who can't use FAFSA-based need aid.",
    url: "https://enrollment.byu.edu/financial-aid/international-student-scholarships",
    requirements: [
      "Enrolled international student (non-U.S. citizen).",
      "Awarded primarily on academic merit.",
      "Check department & Kennedy Center funds too.",
    ],
  },
  {
    id: "byu-spring-summer",
    name: "Spring / Summer Scholarships",
    provider: "BYU Financial Aid Office",
    group: "University",
    award: "Partial tuition for spring/summer terms",
    minGPA: 3.0,
    levels: CONTINUING,
    colleges: ["any"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    deadline: { month: 3, day: 1 },
    deadlineNote: "For students enrolling in spring and/or summer term.",
    url: "https://enrollment.byu.edu/financial-aid/spring-summer-scholarships",
    requirements: [
      "Plan to enroll during spring and/or summer term.",
      "Helps continuing students keep momentum year-round.",
    ],
  },

  /* ---------------- Marriott School of Business ---------------- */
  {
    id: "marriott-general",
    name: "BYU Marriott School Scholarships",
    provider: "BYU Marriott School of Business",
    group: "College",
    award: "Partial to full tuition",
    minGPA: 3.3,
    minCredits: 12,
    levels: CONTINUING,
    colleges: ["marriott"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    deadline: { month: 2, day: 1 },
    deadlineNote: "Application opens Dec 1 and closes Feb 1 (MST). Reapply every year.",
    url: "https://marriott.byu.edu/financialaid/scholarships/",
    requirements: [
      "Admitted to (or majoring in) a Marriott School program.",
      "Considers GPA, need, service, leadership, hometown, and experience.",
      "First-generation students are specifically considered.",
    ],
  },
  {
    id: "marriott-program",
    name: "Marriott Program-Specific Scholarships",
    provider: "BYU Marriott School of Business",
    group: "College",
    award: "Varies by department",
    minGPA: 3.3,
    minCredits: 12,
    levels: CONTINUING,
    colleges: ["marriott"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    deadline: { month: 2, day: 1 },
    deadlineNote: "Same Dec 1 – Feb 1 window as the general Marriott application.",
    url: "https://marriott.byu.edu/financialaid/scholarships/",
    requirements: [
      "For declared majors in a specific program (Accounting, Finance, IS, etc.).",
      "One Marriott application is considered for both general and program awards.",
    ],
  },
  {
    id: "management-society",
    name: "BYU Management Society Scholarships",
    provider: "BYU Marriott School of Business",
    group: "College",
    award: "Varies by chapter",
    minGPA: 3.0,
    minCredits: 12,
    levels: CONTINUING,
    colleges: ["marriott"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    deadline: { month: 2, day: 1 },
    deadlineNote: "Awarded through the Marriott application; tied to local chapter hometowns.",
    url: "https://marriott.byu.edu/financialaid/scholarships/",
    requirements: [
      "Tied to specific Management Society chapter hometowns.",
      "Considered automatically through the Marriott scholarship application.",
    ],
  },

  /* ---------------- Other college scholarships ---------------- */
  {
    id: "engineering-college",
    name: "Fulton College of Engineering Scholarships",
    provider: "Ira A. Fulton College of Engineering",
    group: "College",
    award: "Varies by department",
    minGPA: 3.5,
    minCredits: 12,
    levels: CONTINUING,
    colleges: ["engineering"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    deadline: { month: 2, day: 1 },
    deadlineNote: "Deadlines vary by department — often near the Feb 1 general date.",
    url: "https://engineering.byu.edu/",
    requirements: [
      "Declared major in a Fulton College engineering/technology program.",
      "Strong GPA and progress in major coursework.",
      "Contact your department advisement center for its form.",
    ],
  },
  {
    id: "cpms-college",
    name: "Computing, Math & Physical Sciences Scholarships",
    provider: "College of Computational, Mathematical & Physical Sciences",
    group: "College",
    award: "Varies by department",
    minGPA: 3.5,
    minCredits: 12,
    levels: CONTINUING,
    colleges: ["cpms"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    deadline: { month: 2, day: 1 },
    deadlineNote: "Apply through the college scholarship page; deadlines vary by department.",
    url: "https://science.byu.edu/college-scholarships",
    requirements: [
      "Declared CS, math, physics, chemistry, geology, or statistics major.",
      "Merit-based, with some need consideration.",
    ],
  },
  {
    id: "lifesci-college",
    name: "Life Sciences Scholarships",
    provider: "BYU College of Life Sciences",
    group: "College",
    award: "Varies by department",
    minGPA: 3.5,
    minCredits: 12,
    levels: CONTINUING,
    colleges: ["lifesci"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    deadline: { month: 2, day: 1 },
    deadlineNote: "Offered for Fall & Winter semesters only. Apply through the LSA office.",
    url: "https://lifesciences.byu.edu/lsa/scholarships",
    requirements: [
      "Declared major in a Life Sciences department.",
      "Strong GPA; research involvement helps.",
      "Great fit for pre-med / pre-health students.",
    ],
  },
  {
    id: "education-college",
    name: "McKay School of Education Scholarships",
    provider: "David O. McKay School of Education",
    group: "College",
    award: "Varies by program",
    minGPA: 3.3,
    minCredits: 12,
    levels: CONTINUING,
    colleges: ["education"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    deadline: { month: 2, day: 1 },
    deadlineNote: "Contact msescholarships@byu.edu; deadlines vary by program.",
    url: "https://education.byu.edu/",
    requirements: [
      "Declared major in the McKay School (teaching, special ed, comm. disorders).",
      "Commitment to the education profession.",
    ],
  },
  {
    id: "fhss-college",
    name: "Family, Home & Social Sciences Scholarships",
    provider: "College of Family, Home & Social Sciences",
    group: "College",
    award: "Varies by department",
    minGPA: 3.3,
    minCredits: 12,
    levels: CONTINUING,
    colleges: ["fhss"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    deadline: { month: 2, day: 1 },
    deadlineNote: "Each FHSS department sets its own criteria and deadline.",
    url: "https://fhssadvisement.byu.edu/scholarships",
    requirements: [
      "Declared major in an FHSS department (psychology, history, econ, etc.).",
      "Merit-based, sometimes with need or research components.",
    ],
  },
  {
    id: "finearts-talent",
    name: "Fine Arts & Communications Talent Awards",
    provider: "College of Fine Arts & Communications",
    group: "College",
    award: "$100 to full tuition (one year)",
    minGPA: 0,
    levels: ["incoming-freshman", ...CONTINUING],
    colleges: ["finearts"],
    needBased: false,
    meritBased: true,
    talentBased: true,
    internationalEligible: true,
    deadline: { month: 12, day: 1 },
    deadlineNote: "Audition/portfolio deadlines vary by department — many are in the fall.",
    url: "https://cfac.byu.edu/",
    requirements: [
      "For music, dance, art, theatre, and communications students.",
      "Demonstrated talent matters more than grades — audition or portfolio required.",
      "Awards range from $100 up to full tuition for one year.",
    ],
  },
  {
    id: "humanities-college",
    name: "College of Humanities Scholarships",
    provider: "BYU College of Humanities",
    group: "College",
    award: "Varies by department",
    minGPA: 3.3,
    minCredits: 12,
    levels: CONTINUING,
    colleges: ["humanities"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    deadline: { month: 2, day: 1 },
    deadlineNote: "Language, literature, and philosophy departments each have funds.",
    url: "https://humanities.byu.edu/",
    requirements: [
      "Declared major in a Humanities department.",
      "Language proficiency and study-abroad plans are often rewarded.",
    ],
  },
  {
    id: "nursing-college",
    name: "College of Nursing Scholarships",
    provider: "BYU College of Nursing",
    group: "College",
    award: "Varies",
    minGPA: 3.5,
    minCredits: 12,
    levels: CONTINUING,
    colleges: ["nursing"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    deadline: { month: 2, day: 1 },
    deadlineNote: "Contact nursing_advisement@byu.edu for current forms and dates.",
    url: "https://nursing.byu.edu/",
    requirements: [
      "Admitted to the competitive nursing program.",
      "Strong GPA and clinical progress.",
    ],
  },

  /* ---------------- Institutes ---------------- */
  {
    id: "wheatley-scholars",
    name: "Wheatley Scholars (Jack & Lois Wheatley Endowed Leadership Scholarship)",
    provider: "Wheatley Institute",
    group: "Institute",
    award: "130% of full tuition for your last 4 semesters (+ possible grad support)",
    minGPA: 3.7,
    minCredits: 12,
    levels: ["sophomore", "junior"],
    colleges: ["any"],
    needBased: false,
    meritBased: true,
    internationalEligible: true,
    deadline: { month: 11, day: 1 },
    deadlineNote: "Apply in the fall ~2 years before graduation. Verify the exact date on the site.",
    url: "https://wheatley.byu.edu/scholarship-application",
    requirements: [
      "On track to graduate about two years out (apply as a sophomore/junior).",
      "Passionate about the family, religion, and constitutional government.",
      "Complete a faculty-mentored academic project beyond normal coursework.",
      "Attend Wheatley gatherings and volunteer at events as a scholar.",
    ],
  },
  {
    id: "kennedy-global-opportunity",
    name: "Global Opportunity Scholarship",
    provider: "BYU Kennedy Center",
    group: "Institute",
    award: "Up to $5,000 (need-based)",
    minGPA: 0,
    levels: ["freshman", "sophomore", "junior", "senior", "transfer"],
    colleges: ["any"],
    needBased: true,
    meritBased: false,
    internationalEligible: true,
    studyAbroad: true,
    deadline: { month: 12, day: 1 },
    deadlineNote: "Spring/summer nomination deadline is Dec 1.",
    url: "https://kennedy.byu.edu/globalopportunity",
    requirements: [
      "For your FIRST academic experience abroad through a BYU program.",
      "Open to ANY major and college — including international & married students.",
      "Meet with your program's faculty director to be nominated.",
    ],
  },
  {
    id: "kennedy-education-abroad",
    name: "Fund for Education Abroad & other ISP Scholarships",
    provider: "BYU Kennedy Center",
    group: "Institute",
    award: "Varies (study abroad support)",
    minGPA: 0,
    levels: ["freshman", "sophomore", "junior", "senior", "transfer"],
    colleges: ["any"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    studyAbroad: true,
    deadline: { month: 12, day: 1 },
    deadlineNote: "Aligns with international study program deadlines — check per program.",
    url: "https://kennedy.byu.edu/scholarships",
    requirements: [
      "Participating in a BYU international study program.",
      "Take the Kennedy Center funding survey to see everything you qualify for.",
      "Several funds can stack with the Global Opportunity Scholarship.",
    ],
  },

  /* ---------------- Special ---------------- */
  {
    id: "rotc",
    name: "ROTC Scholarships (Army & Air Force)",
    provider: "BYU Army / Air Force ROTC",
    group: "Special",
    award: "Up to full tuition + stipend & book allowance",
    minGPA: 2.5,
    levels: ["incoming-freshman", ...CONTINUING],
    colleges: ["any"],
    needBased: false,
    meritBased: true,
    internationalEligible: false,
    deadline: { month: 1, day: 31 },
    deadlineNote: "Timelines vary — apply early and talk to the ROTC recruiting officer.",
    url: "https://armyrotc.byu.edu/",
    requirements: [
      "U.S. citizen willing to commission and serve after graduation.",
      "Meet fitness and academic standards.",
      "Open to almost any major.",
    ],
  },
  {
    id: "athletic",
    name: "Athletic Scholarships",
    provider: "BYU Athletics",
    group: "Special",
    award: "Partial to full cost of attendance",
    minGPA: 2.0,
    levels: ["incoming-freshman", ...CONTINUING],
    colleges: ["any"],
    needBased: false,
    meritBased: false,
    talentBased: true,
    internationalEligible: true,
    deadline: null,
    deadlineNote: "Recruited student-athletes only — contact the coaching staff directly.",
    url: "https://byucougars.com/",
    requirements: [
      "Recruited by a BYU varsity team.",
      "Meet NCAA eligibility standards.",
      "Awarded by the coaching staff, not a standard application.",
    ],
  },
];
