/*
 * data.js - AI Scholarship Matcher dataset
 * -------------------------------------------------------------
 * Two scopes of scholarships:
 *   scope: "byu"      - BYU internal awards (colleges, institutes, offices)
 *   scope: "national" - awards any student can pursue, matched on
 *                       talents and skills (athletics, arts, leadership,
 *                       academics, service, STEM, and so on)
 *
 * Field notes:
 *   tags         - talent/skill categories that boost the match score
 *   requiredTags - if present, the student must have at least one of
 *                  these talents selected or the award is skipped
 *   sourceType   - "official" (verified on the provider's own site) or
 *                  "secondary" (aggregator data; verify before relying on it)
 *   stacking     - how the award combines with other aid
 *   deadline     - recurring {month, day}; null = rolling or varies
 *
 * Always verify amounts and exact deadlines on the linked page.
 * Data last reviewed: July 2026.
 * -------------------------------------------------------------
 */

// BYU colleges (key -> display label). "undeclared" is a catch-all.
const COLLEGES = {
  marriott: "Marriott School of Business",
  cpms: "Computing, Mathematical & Physical Sciences",
  engineering: "Ira A. Fulton College of Engineering",
  education: "McKay School of Education",
  fhss: "Family, Home & Social Sciences",
  finearts: "Fine Arts & Communications",
  humanities: "College of Humanities",
  lifesci: "College of Life Sciences",
  nursing: "College of Nursing",
  undeclared: "Undeclared / Other",
};

// Talent & skill categories used for matching.
const TALENTS = [
  { value: "athletics", label: "Athletics & sports" },
  { value: "arts", label: "Visual & performing arts" },
  { value: "writing", label: "Writing" },
  { value: "leadership", label: "Leadership" },
  { value: "service", label: "Community service" },
  { value: "stem", label: "STEM & research" },
  { value: "public-service", label: "Government & public service" },
  { value: "environment", label: "Environment & conservation" },
];

// Every major carries the college key that drives BYU scholarship matching.
const MAJORS = [
  { value: "undecided", label: "Undecided / Exploring", college: "undeclared" },

  // Marriott School of Business
  { value: "accounting", label: "Accounting", college: "marriott" },
  { value: "finance", label: "Finance", college: "marriott" },
  { value: "information-systems", label: "Information Systems", college: "marriott" },
  { value: "marketing", label: "Marketing", college: "marriott" },
  { value: "entrepreneurship", label: "Entrepreneurship", college: "marriott" },
  { value: "supply-chain", label: "Global Supply Chain Management", college: "marriott" },
  { value: "human-resources", label: "Human Resource Management", college: "marriott" },
  { value: "experience-design", label: "Experience Design & Management", college: "marriott" },
  { value: "strategy", label: "Strategic Management", college: "marriott" },

  // Computing, Mathematical & Physical Sciences
  { value: "computer-science", label: "Computer Science", college: "cpms" },
  { value: "chemistry", label: "Chemistry", college: "cpms" },
  { value: "biochemistry", label: "Biochemistry", college: "cpms" },
  { value: "geology", label: "Geology", college: "cpms" },
  { value: "mathematics", label: "Mathematics", college: "cpms" },
  { value: "applied-math", label: "Applied & Computational Mathematics", college: "cpms" },
  { value: "math-education", label: "Mathematics Education", college: "cpms" },
  { value: "physics", label: "Physics & Astronomy", college: "cpms" },
  { value: "statistics", label: "Statistics", college: "cpms" },
  { value: "data-science", label: "Data Science", college: "cpms" },

  // Ira A. Fulton College of Engineering
  { value: "chemical-engineering", label: "Chemical Engineering", college: "engineering" },
  { value: "civil-engineering", label: "Civil Engineering", college: "engineering" },
  { value: "construction-management", label: "Construction & Facilities Management", college: "engineering" },
  { value: "electrical-engineering", label: "Electrical Engineering", college: "engineering" },
  { value: "computer-engineering", label: "Computer Engineering", college: "engineering" },
  { value: "mechanical-engineering", label: "Mechanical Engineering", college: "engineering" },
  { value: "manufacturing-engineering", label: "Manufacturing Engineering", college: "engineering" },
  { value: "software-engineering", label: "Software Engineering", college: "engineering" },
  { value: "information-technology", label: "Information Technology", college: "engineering" },
  { value: "cybersecurity", label: "Cybersecurity", college: "engineering" },
  { value: "tech-engineering-studies", label: "Technology & Engineering Studies", college: "engineering" },

  // McKay School of Education
  { value: "elementary-education", label: "Elementary Education", college: "education" },
  { value: "early-childhood", label: "Early Childhood Education", college: "education" },
  { value: "special-education", label: "Special Education", college: "education" },
  { value: "communication-disorders", label: "Communication Disorders", college: "education" },

  // Family, Home & Social Sciences
  { value: "economics", label: "Economics", college: "fhss" },
  { value: "anthropology", label: "Anthropology", college: "fhss" },
  { value: "family-life", label: "Family Life / Human Development", college: "fhss" },
  { value: "geography", label: "Geography", college: "fhss" },
  { value: "geospatial", label: "Geospatial Intelligence", college: "fhss" },
  { value: "history", label: "History", college: "fhss" },
  { value: "political-science", label: "Political Science", college: "fhss" },
  { value: "psychology", label: "Psychology", college: "fhss" },
  { value: "social-work", label: "Social Work", college: "fhss" },
  { value: "sociology", label: "Sociology", college: "fhss" },

  // Fine Arts & Communications
  { value: "communications", label: "Communications (Journalism / PR / Ad)", college: "finearts" },
  { value: "studio-art", label: "Studio Arts", college: "finearts" },
  { value: "art-history", label: "Art History & Curatorial Studies", college: "finearts" },
  { value: "art-education", label: "Art Education", college: "finearts" },
  { value: "animation", label: "Animation", college: "finearts" },
  { value: "graphic-design", label: "Graphic Design", college: "finearts" },
  { value: "illustration", label: "Illustration", college: "finearts" },
  { value: "photography", label: "Photography", college: "finearts" },
  { value: "industrial-design", label: "Industrial Design", college: "finearts" },
  { value: "dance", label: "Dance", college: "finearts" },
  { value: "music", label: "Music", college: "finearts" },
  { value: "music-education", label: "Music Education", college: "finearts" },
  { value: "commercial-music", label: "Commercial Music", college: "finearts" },
  { value: "media-arts", label: "Media Arts Studies (Film)", college: "finearts" },
  { value: "theatre", label: "Theatre Arts", college: "finearts" },

  // College of Humanities
  { value: "english", label: "English", college: "humanities" },
  { value: "english-language", label: "English Language / Editing & Publishing", college: "humanities" },
  { value: "linguistics", label: "Linguistics", college: "humanities" },
  { value: "philosophy", label: "Philosophy", college: "humanities" },
  { value: "french", label: "French Studies", college: "humanities" },
  { value: "italian", label: "Italian Studies", college: "humanities" },
  { value: "german", label: "German Studies", college: "humanities" },
  { value: "russian", label: "Russian", college: "humanities" },
  { value: "spanish", label: "Spanish", college: "humanities" },
  { value: "portuguese", label: "Portuguese", college: "humanities" },
  { value: "chinese", label: "Chinese", college: "humanities" },
  { value: "japanese", label: "Japanese", college: "humanities" },
  { value: "korean", label: "Korean", college: "humanities" },
  { value: "asian-studies", label: "Asian Studies", college: "humanities" },
  { value: "ancient-near-eastern", label: "Ancient Near Eastern Studies", college: "humanities" },
  { value: "classics", label: "Classical Studies (Greek / Latin)", college: "humanities" },
  { value: "comparative-lit", label: "Comparative Literature", college: "humanities" },
  { value: "translation", label: "Translation & Localization", college: "humanities" },
  { value: "american-studies", label: "American Studies", college: "humanities" },

  // College of Life Sciences
  { value: "biology", label: "Biology", college: "lifesci" },
  { value: "biology-education", label: "Biology Education", college: "lifesci" },
  { value: "physiology", label: "Physiology & Developmental Biology", college: "lifesci" },
  { value: "exercise-science", label: "Exercise & Wellness / Exercise Science", college: "lifesci" },
  { value: "athletic-training", label: "Athletic Training", college: "lifesci" },
  { value: "microbiology", label: "Microbiology", college: "lifesci" },
  { value: "molecular-biology", label: "Molecular Biology", college: "lifesci" },
  { value: "biotechnology", label: "Biotechnology", college: "lifesci" },
  { value: "neuroscience", label: "Neuroscience", college: "lifesci" },
  { value: "nutrition", label: "Nutritional Science", college: "lifesci" },
  { value: "dietetics", label: "Dietetics", college: "lifesci" },
  { value: "food-science", label: "Food Science", college: "lifesci" },
  { value: "plant-science", label: "Plant & Wildlife Sciences", college: "lifesci" },
  { value: "wildlife", label: "Wildlife & Wildlands Conservation", college: "lifesci" },
  { value: "environmental-science", label: "Environmental Science", college: "lifesci" },
  { value: "public-health", label: "Public Health", college: "lifesci" },
  { value: "genetics", label: "Genetics, Genomics & Biotechnology", college: "lifesci" },

  // College of Nursing
  { value: "nursing", label: "Nursing", college: "nursing" },

  { value: "other", label: "Other / Not listed", college: "undeclared" },
];

const LEVELS = [
  { value: "incoming-freshman", label: "High school student / incoming freshman" },
  { value: "freshman", label: "Freshman (current)" },
  { value: "sophomore", label: "Sophomore" },
  { value: "junior", label: "Junior" },
  { value: "senior", label: "Senior" },
  { value: "transfer", label: "Transfer student" },
];

const CONTINUING = ["freshman", "sophomore", "junior", "senior", "transfer"];

const SCHOLARSHIPS = [
  /* ================= BYU: University-wide (Financial Aid Office) ================= */
  {
    id: "byu-freshman-merit",
    name: "New Freshman Scholarships (Presidential, Heritage, etc.)",
    provider: "BYU Financial Aid Office",
    scope: "byu",
    group: "University",
    award: "Half to full tuition (award tiers by academic index)",
    minGPA: 3.7,
    levels: ["incoming-freshman"],
    colleges: ["any"],
    needBased: false,
    meritBased: true,
    internationalEligible: true,
    tags: [],
    deadline: { month: 12, day: 15 },
    deadlineNote: "Awarded automatically from your admissions application. No separate form.",
    sourceType: "official",
    stacking: "Stacks with department, institute, and outside awards up to the cost of attendance.",
    url: "https://enrollment.byu.edu/financial-aid/new-freshman-scholarships",
    requirements: [
      "Considered automatically when you apply for admission.",
      "Ranked on an academic index (high-school GPA + test scores).",
      "Higher index = higher award tier, up to full tuition.",
    ],
  },
  {
    id: "byu-continuing-academic",
    name: "Continuing Student Academic Scholarship",
    provider: "BYU Financial Aid Office",
    scope: "byu",
    group: "University",
    award: "Half to full LDS tuition (GPA cutoff varies yearly)",
    minGPA: 3.7,
    minCredits: 12,
    levels: CONTINUING,
    colleges: ["any"],
    needBased: false,
    meritBased: true,
    internationalEligible: true,
    tags: [],
    deadline: { month: 2, day: 1 },
    deadlineNote: "General deadline Feb 1; submit the FAFSA by Jan 20 for need consideration.",
    sourceType: "official",
    stacking: "One application also covers private donor funds. Combines with college and department awards.",
    url: "https://enrollment.byu.edu/financial-aid/former-continuing-student-scholarships",
    requirements: [
      "Complete at least 12 BYU credit hours by the end of fall semester.",
      "Meet the cumulative GPA cutoff (set yearly by college, competitive).",
      "Multi-year awards require maintaining a 3.70 cumulative GPA.",
    ],
  },
  {
    id: "byu-need-based",
    name: "Need-Based Scholarships (incl. Cougar Pell Promise / Elevated)",
    provider: "BYU Financial Aid Office",
    scope: "byu",
    group: "University",
    award: "Half to full LDS tuition (need-based)",
    minGPA: 2.5,
    levels: ["incoming-freshman", ...CONTINUING],
    colleges: ["any"],
    needBased: true,
    meritBased: false,
    internationalEligible: false,
    tags: [],
    deadline: { month: 1, day: 20 },
    deadlineNote: "Requires the FAFSA. Submit by Jan 20.",
    sourceType: "official",
    stacking: "Combines with academic and department awards; total aid is capped at cost of attendance.",
    url: "https://enrollment.byu.edu/financial-aid/former-continuing-student-scholarships",
    requirements: [
      "Submit the FAFSA by January 20.",
      "Demonstrated financial need (Pell-eligible students prioritized).",
      "U.S. citizen or eligible non-citizen (FAFSA requirement).",
    ],
  },
  {
    id: "byu-private-donor",
    name: "Private Donor Scholarships (administered by BYU)",
    provider: "BYU Financial Aid Office",
    scope: "byu",
    group: "University",
    award: "Half or full LDS tuition (varies by donor)",
    minGPA: 3.0,
    levels: CONTINUING,
    colleges: ["any"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    tags: [],
    deadline: { month: 2, day: 1 },
    deadlineNote: "Considered with the general Feb 1 scholarship application.",
    sourceType: "official",
    stacking: "One application feeds many donor funds automatically.",
    url: "https://enrollment.byu.edu/financial-aid/former-continuing-student-scholarships",
    requirements: [
      "Criteria set by the donor, often hometown, high school, or family ties.",
      "Mix of need-based and merit-based funds.",
      "One application covers you for many donor funds automatically.",
    ],
  },
  {
    id: "byu-transfer",
    name: "Transfer Student Scholarships",
    provider: "BYU Financial Aid Office",
    scope: "byu",
    group: "University",
    award: "Varies (merit + need)",
    minGPA: 3.5,
    levels: ["transfer"],
    colleges: ["any"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    tags: [],
    deadline: { month: 2, day: 1 },
    deadlineNote: "Complete 12+ BYU credits before you're eligible for FA academic awards.",
    sourceType: "official",
    stacking: "Combines with department and institute awards.",
    url: "https://enrollment.byu.edu/financial-aid/transfer-students-scholarships",
    requirements: [
      "Transfer at least 12 credits of regular coursework.",
      "Strong transfer GPA (competitive).",
      "Some awards recognize your first semesters at BYU.",
    ],
  },
  {
    id: "byu-international",
    name: "International Student Scholarships",
    provider: "BYU Financial Aid Office",
    scope: "byu",
    group: "University",
    award: "Varies (merit-based)",
    minGPA: 3.5,
    levels: ["incoming-freshman", ...CONTINUING],
    colleges: ["any"],
    needBased: false,
    meritBased: true,
    internationalEligible: true,
    internationalOnly: true,
    tags: [],
    deadline: { month: 2, day: 1 },
    deadlineNote: "For international students who can't use FAFSA-based need aid.",
    sourceType: "official",
    stacking: "Check department and Kennedy Center funds too; most combine.",
    url: "https://enrollment.byu.edu/financial-aid/international-student-scholarships",
    requirements: [
      "Enrolled international student (non-U.S. citizen).",
      "Awarded primarily on academic merit.",
      "Check department & Kennedy Center funds too.",
    ],
  },
  {
    id: "byu-spring-summer",
    name: "Spring / Summer Scholarships",
    provider: "BYU Financial Aid Office",
    scope: "byu",
    group: "University",
    award: "Partial tuition for spring/summer terms",
    minGPA: 3.0,
    levels: CONTINUING,
    colleges: ["any"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    tags: [],
    deadline: { month: 3, day: 1 },
    deadlineNote: "For students enrolling in spring and/or summer term.",
    sourceType: "official",
    stacking: "Separate budget from fall/winter awards, so it adds on top.",
    url: "https://enrollment.byu.edu/financial-aid/spring-summer-scholarships",
    requirements: [
      "Plan to enroll during spring and/or summer term.",
      "Helps continuing students keep momentum year-round.",
    ],
  },

  /* ================= BYU: Marriott School of Business ================= */
  {
    id: "marriott-general",
    name: "BYU Marriott School Scholarships",
    provider: "BYU Marriott School of Business",
    scope: "byu",
    group: "College",
    award: "Partial to full tuition",
    minGPA: 3.3,
    minCredits: 12,
    levels: CONTINUING,
    colleges: ["marriott"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    tags: ["leadership", "service"],
    deadline: { month: 2, day: 1 },
    deadlineNote: "Application opens Dec 1 and closes Feb 1 (MST). Reapply every year.",
    sourceType: "official",
    stacking: "Considered alongside university awards; college and university funds come from different budgets.",
    url: "https://marriott.byu.edu/financialaid/scholarships/",
    requirements: [
      "Admitted to (or majoring in) a Marriott School program.",
      "Considers GPA, need, service, leadership, hometown, and experience.",
      "First-generation students are specifically considered.",
    ],
  },
  {
    id: "marriott-program",
    name: "Marriott Program-Specific Scholarships",
    provider: "BYU Marriott School of Business",
    scope: "byu",
    group: "College",
    award: "Varies by department",
    minGPA: 3.3,
    minCredits: 12,
    levels: CONTINUING,
    colleges: ["marriott"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    tags: [],
    deadline: { month: 2, day: 1 },
    deadlineNote: "Same Dec 1 to Feb 1 window as the general Marriott application.",
    sourceType: "official",
    stacking: "One Marriott application is considered for both general and program awards.",
    url: "https://marriott.byu.edu/financialaid/scholarships/",
    requirements: [
      "For declared majors in a specific program (Accounting, Finance, IS, etc.).",
      "One Marriott application is considered for both general and program awards.",
    ],
  },
  {
    id: "management-society",
    name: "BYU Management Society Scholarships",
    provider: "BYU Marriott School of Business",
    scope: "byu",
    group: "College",
    award: "Varies by chapter",
    minGPA: 3.0,
    minCredits: 12,
    levels: CONTINUING,
    colleges: ["marriott"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    tags: [],
    deadline: { month: 2, day: 1 },
    deadlineNote: "Awarded through the Marriott application; tied to local chapter hometowns.",
    sourceType: "official",
    stacking: "Considered automatically through the Marriott scholarship application.",
    url: "https://marriott.byu.edu/financialaid/scholarships/",
    requirements: [
      "Tied to specific Management Society chapter hometowns.",
      "Considered automatically through the Marriott scholarship application.",
    ],
  },

  /* ================= BYU: Other colleges ================= */
  {
    id: "engineering-college",
    name: "Fulton College of Engineering Scholarships",
    provider: "Ira A. Fulton College of Engineering",
    scope: "byu",
    group: "College",
    award: "Varies by department",
    minGPA: 3.5,
    minCredits: 12,
    levels: CONTINUING,
    colleges: ["engineering"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    tags: ["stem"],
    deadline: { month: 2, day: 1 },
    deadlineNote: "Deadlines vary by department, often near the Feb 1 general date.",
    sourceType: "official",
    stacking: "Adds on top of university awards.",
    url: "https://engineering.byu.edu/",
    requirements: [
      "Declared major in a Fulton College engineering/technology program.",
      "Strong GPA and progress in major coursework.",
      "Contact your department advisement center for its form.",
    ],
  },
  {
    id: "cpms-college",
    name: "Computing, Math & Physical Sciences Scholarships",
    provider: "College of Computational, Mathematical & Physical Sciences",
    scope: "byu",
    group: "College",
    award: "Varies by department",
    minGPA: 3.5,
    minCredits: 12,
    levels: CONTINUING,
    colleges: ["cpms"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    tags: ["stem"],
    deadline: { month: 2, day: 1 },
    deadlineNote: "Apply through the college scholarship page; deadlines vary by department.",
    sourceType: "official",
    stacking: "Adds on top of university awards.",
    url: "https://science.byu.edu/college-scholarships",
    requirements: [
      "Declared CS, math, physics, chemistry, geology, or statistics major.",
      "Merit-based, with some need consideration.",
    ],
  },
  {
    id: "lifesci-college",
    name: "Life Sciences Scholarships",
    provider: "BYU College of Life Sciences",
    scope: "byu",
    group: "College",
    award: "Varies by department",
    minGPA: 3.5,
    minCredits: 12,
    levels: CONTINUING,
    colleges: ["lifesci"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    tags: ["stem"],
    deadline: { month: 2, day: 1 },
    deadlineNote: "Offered for Fall & Winter semesters only. Apply through the LSA office.",
    sourceType: "official",
    stacking: "Adds on top of university awards.",
    url: "https://lifesciences.byu.edu/lsa/scholarships",
    requirements: [
      "Declared major in a Life Sciences department.",
      "Strong GPA; research involvement helps.",
      "Great fit for pre-med / pre-health students.",
    ],
  },
  {
    id: "education-college",
    name: "McKay School of Education Scholarships",
    provider: "David O. McKay School of Education",
    scope: "byu",
    group: "College",
    award: "Varies by program",
    minGPA: 3.3,
    minCredits: 12,
    levels: CONTINUING,
    colleges: ["education"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    tags: ["service"],
    deadline: { month: 2, day: 1 },
    deadlineNote: "Contact msescholarships@byu.edu; deadlines vary by program.",
    sourceType: "official",
    stacking: "Adds on top of university awards.",
    url: "https://education.byu.edu/",
    requirements: [
      "Declared major in the McKay School (teaching, special ed, comm. disorders).",
      "Commitment to the education profession.",
    ],
  },
  {
    id: "fhss-college",
    name: "Family, Home & Social Sciences Scholarships",
    provider: "College of Family, Home & Social Sciences",
    scope: "byu",
    group: "College",
    award: "Varies by department",
    minGPA: 3.3,
    minCredits: 12,
    levels: CONTINUING,
    colleges: ["fhss"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    tags: [],
    deadline: { month: 2, day: 1 },
    deadlineNote: "Each FHSS department sets its own criteria and deadline.",
    sourceType: "official",
    stacking: "Adds on top of university awards.",
    url: "https://fhssadvisement.byu.edu/scholarships",
    requirements: [
      "Declared major in an FHSS department (psychology, history, econ, etc.).",
      "Merit-based, sometimes with need or research components.",
    ],
  },
  {
    id: "finearts-talent",
    name: "Fine Arts & Communications Talent Awards",
    provider: "College of Fine Arts & Communications",
    scope: "byu",
    group: "College",
    award: "$100 to full tuition (one year)",
    minGPA: 0,
    levels: ["incoming-freshman", ...CONTINUING],
    colleges: ["finearts"],
    needBased: false,
    meritBased: true,
    talentBased: true,
    internationalEligible: true,
    tags: ["arts"],
    deadline: { month: 12, day: 1 },
    deadlineNote: "Audition/portfolio deadlines vary by department; many are in the fall.",
    sourceType: "official",
    stacking: "Talent awards combine with academic and need awards.",
    url: "https://cfac.byu.edu/",
    requirements: [
      "For music, dance, art, theatre, and communications students.",
      "Demonstrated talent matters more than grades. Audition or portfolio required.",
      "Awards range from $100 up to full tuition for one year.",
    ],
  },
  {
    id: "humanities-college",
    name: "College of Humanities Scholarships",
    provider: "BYU College of Humanities",
    scope: "byu",
    group: "College",
    award: "Varies by department",
    minGPA: 3.3,
    minCredits: 12,
    levels: CONTINUING,
    colleges: ["humanities"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    tags: ["writing"],
    deadline: { month: 2, day: 1 },
    deadlineNote: "Language, literature, and philosophy departments each have funds.",
    sourceType: "official",
    stacking: "Adds on top of university awards.",
    url: "https://humanities.byu.edu/",
    requirements: [
      "Declared major in a Humanities department.",
      "Language proficiency and study-abroad plans are often rewarded.",
    ],
  },
  {
    id: "nursing-college",
    name: "College of Nursing Scholarships",
    provider: "BYU College of Nursing",
    scope: "byu",
    group: "College",
    award: "Varies",
    minGPA: 3.5,
    minCredits: 12,
    levels: CONTINUING,
    colleges: ["nursing"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    tags: ["service"],
    deadline: { month: 2, day: 1 },
    deadlineNote: "Contact nursing_advisement@byu.edu for current forms and dates.",
    sourceType: "official",
    stacking: "Adds on top of university awards.",
    url: "https://nursing.byu.edu/",
    requirements: [
      "Admitted to the competitive nursing program.",
      "Strong GPA and clinical progress.",
    ],
  },

  /* ================= BYU: Institutes & programs ================= */
  {
    id: "wheatley-scholars",
    name: "Wheatley Scholars (Jack & Lois Wheatley Endowed Leadership Scholarship)",
    provider: "Wheatley Institute",
    scope: "byu",
    group: "Institute",
    award: "130% of full tuition for your last 4 semesters (+ possible grad support)",
    minGPA: 3.7,
    minCredits: 12,
    levels: ["sophomore", "junior"],
    colleges: ["any"],
    needBased: false,
    meritBased: true,
    internationalEligible: true,
    tags: ["leadership", "public-service"],
    deadline: { month: 11, day: 1 },
    deadlineNote: "Apply in the fall about 2 years before graduation. Verify the exact date on the site.",
    sourceType: "official",
    stacking: "Because the award exceeds tuition, it can replace rather than stack with tuition awards. Ask the institute.",
    url: "https://wheatley.byu.edu/scholarship-application",
    requirements: [
      "On track to graduate about two years out (apply as a sophomore/junior).",
      "Passionate about the family, religion, and constitutional government.",
      "Complete a faculty-mentored academic project beyond normal coursework.",
      "Attend Wheatley gatherings and volunteer at events as a scholar.",
    ],
  },
  {
    id: "kennedy-global-opportunity",
    name: "Global Opportunity Scholarship",
    provider: "BYU Kennedy Center",
    scope: "byu",
    group: "Institute",
    award: "Up to $5,000 (need-based)",
    minGPA: 0,
    levels: ["freshman", "sophomore", "junior", "senior", "transfer"],
    colleges: ["any"],
    needBased: true,
    meritBased: false,
    internationalEligible: true,
    studyAbroad: true,
    tags: [],
    deadline: { month: 12, day: 1 },
    deadlineNote: "Spring/summer nomination deadline is Dec 1.",
    sourceType: "official",
    stacking: "Stacks with other Kennedy Center funds and university awards.",
    url: "https://kennedy.byu.edu/globalopportunity",
    requirements: [
      "For your FIRST academic experience abroad through a BYU program.",
      "Open to ANY major and college, including international and married students.",
      "Meet with your program's faculty director to be nominated.",
    ],
  },
  {
    id: "kennedy-education-abroad",
    name: "Fund for Education Abroad & other ISP Scholarships",
    provider: "BYU Kennedy Center",
    scope: "byu",
    group: "Institute",
    award: "Varies (study abroad support)",
    minGPA: 0,
    levels: ["freshman", "sophomore", "junior", "senior", "transfer"],
    colleges: ["any"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    studyAbroad: true,
    tags: [],
    deadline: { month: 12, day: 1 },
    deadlineNote: "Aligns with international study program deadlines. Check per program.",
    sourceType: "official",
    stacking: "Several funds can stack with the Global Opportunity Scholarship.",
    url: "https://kennedy.byu.edu/scholarships",
    requirements: [
      "Participating in a BYU international study program.",
      "Take the Kennedy Center funding survey to see everything you qualify for.",
      "Several funds can stack with the Global Opportunity Scholarship.",
    ],
  },
  {
    id: "byu-phi-kappa-phi",
    name: "Phi Kappa Phi BYU Chapter Scholarships (Brasher & Ellsworth)",
    provider: "Phi Kappa Phi, BYU Chapter",
    scope: "byu",
    group: "Institute",
    award: "Varies by year (chapter-funded awards)",
    minGPA: 3.8,
    levels: ["junior", "senior"],
    colleges: ["any"],
    needBased: false,
    meritBased: true,
    internationalEligible: true,
    tags: [],
    deadline: { month: 2, day: 15 },
    deadlineNote: "Local chapter awards have closed Feb 15 in recent cycles; the national fellowship (for grad school) runs on its own April deadline.",
    sourceType: "official",
    stacking: "Chapter awards combine with university aid. The national fellowship is separate money for graduate study.",
    url: "https://phikappaphi.byu.edu/phi-kappa-phi-awards-summary",
    requirements: [
      "Membership eligibility: top of your class as a junior or senior (invitation-based).",
      "Local awards (Ruth E. Brasher and Carol A. Ellsworth scholarships) require a short application.",
      "Seniors headed to grad school can also compete for the national Phi Kappa Phi Fellowship.",
    ],
  },
  {
    id: "byu-honors",
    name: "BYU Honors Program Scholarships",
    provider: "BYU Honors Program",
    scope: "byu",
    group: "Institute",
    award: "Varies (early-career and thesis awards, plus research funding)",
    minGPA: 3.5,
    levels: CONTINUING,
    colleges: ["any"],
    needBased: true,
    meritBased: true,
    internationalEligible: true,
    tags: ["stem", "writing"],
    deadline: { month: 7, day: 31 },
    deadlineNote: "Fall deadline July 31; winter deadline Oct 30. Verify on the Honors site.",
    sourceType: "official",
    stacking: "Honors awards add to university and college aid, and thesis grants can cover research costs separately.",
    url: "https://honors.byu.edu/scholarships",
    requirements: [
      "Enrolled in (or joining) the BYU Honors Program.",
      "Awards for students early in their Honors career and for students writing the Honors thesis.",
      "Some named funds favor first-generation students with financial need.",
      "Extra funding available for thesis research, conferences, or publication.",
    ],
  },

  /* ================= BYU: Special ================= */
  {
    id: "rotc",
    name: "ROTC Scholarships (Army & Air Force)",
    provider: "BYU Army / Air Force ROTC",
    scope: "byu",
    group: "Special",
    award: "Up to full tuition + stipend & book allowance",
    minGPA: 2.5,
    levels: ["incoming-freshman", ...CONTINUING],
    colleges: ["any"],
    needBased: false,
    meritBased: true,
    internationalEligible: false,
    tags: ["leadership", "athletics"],
    deadline: { month: 1, day: 31 },
    deadlineNote: "Timelines vary. Apply early and talk to the ROTC recruiting officer.",
    sourceType: "official",
    stacking: "ROTC benefits usually replace tuition awards but stack with housing and book aid. Confirm with the detachment.",
    url: "https://armyrotc.byu.edu/",
    requirements: [
      "U.S. citizen willing to commission and serve after graduation.",
      "Meet fitness and academic standards.",
      "Open to almost any major.",
    ],
  },
  {
    id: "athletic",
    name: "BYU Athletic Scholarships",
    provider: "BYU Athletics",
    scope: "byu",
    group: "Special",
    award: "Partial to full cost of attendance",
    minGPA: 2.0,
    levels: ["incoming-freshman", ...CONTINUING],
    colleges: ["any"],
    needBased: false,
    meritBased: false,
    talentBased: true,
    internationalEligible: true,
    tags: ["athletics"],
    requiredTags: ["athletics"],
    deadline: null,
    deadlineNote: "Recruited student-athletes only. Contact the coaching staff directly.",
    sourceType: "official",
    stacking: "Governed by NCAA rules; full-ride athletes generally can't stack tuition awards.",
    url: "https://byucougars.com/",
    requirements: [
      "Recruited by a BYU varsity team.",
      "Meet NCAA eligibility standards.",
      "Awarded by the coaching staff, not a standard application.",
    ],
  },

  /* ================= National: academics & leadership ================= */
  {
    id: "coca-cola-scholars",
    name: "Coca-Cola Scholars Program",
    provider: "Coca-Cola Scholars Foundation",
    scope: "national",
    group: "National",
    award: "$20,000 (150 awards per year)",
    minGPA: 3.0,
    levels: ["incoming-freshman"],
    colleges: ["any"],
    needBased: false,
    meritBased: true,
    internationalEligible: false,
    tags: ["leadership", "service"],
    deadline: { month: 9, day: 30 },
    deadlineNote: "Applications open in August and close September 30 (5 pm ET). Apply as a high school senior.",
    sourceType: "official",
    stacking: "Outside award. It stacks with university aid but can reduce need-based grants; report it to your financial aid office.",
    url: "https://www.coca-colascholarsfoundation.org/apply/",
    requirements: [
      "High school senior; U.S. citizen or eligible non-citizen.",
      "3.0+ GPA throughout high school.",
      "Judged on leadership, service, and impact in school and community.",
      "Very competitive: roughly 150 winners from 100,000+ applicants.",
    ],
  },
  {
    id: "elks-mvs",
    name: "Elks Most Valuable Student Scholarship",
    provider: "Elks National Foundation",
    scope: "national",
    group: "National",
    award: "$4,000 to $30,000 (500 awards per year)",
    minGPA: 0,
    levels: ["incoming-freshman"],
    colleges: ["any"],
    needBased: true,
    meritBased: true,
    internationalEligible: false,
    tags: ["leadership", "service"],
    deadline: { month: 11, day: 12 },
    deadlineNote: "Closes in mid November for the following school year. Verify the exact date each cycle.",
    sourceType: "official",
    stacking: "Outside award paid over four years; stacks with university aid up to cost of attendance.",
    url: "https://www.elks.org/scholars/scholarships/mvs.cfm",
    requirements: [
      "Current high school senior; U.S. citizen.",
      "Judged on scholarship, leadership, and financial need.",
      "Top 20 finalists receive $30,000; 480 runners-up receive $4,000.",
    ],
  },
  {
    id: "ge-reagan",
    name: "GE-Reagan Foundation Scholarship",
    provider: "Ronald Reagan Presidential Foundation",
    scope: "national",
    group: "National",
    award: "$10,000 per year, renewable up to $40,000",
    minGPA: 3.0,
    levels: ["incoming-freshman"],
    colleges: ["any"],
    needBased: false,
    meritBased: true,
    internationalEligible: false,
    tags: ["leadership", "service"],
    deadline: { month: 1, day: 5 },
    deadlineNote: "Complete applications due early January (noon CT). Verify the date each cycle.",
    sourceType: "official",
    stacking: "Renewable outside award; stacks with university aid but must be reported.",
    url: "https://www.reaganfoundation.org/education/ge-reagan-foundation-scholarship",
    requirements: [
      "High school senior; U.S. citizen.",
      "Demonstrates leadership, drive, integrity, and citizenship.",
      "Requires an essay on leadership and service plus a recommendation.",
    ],
  },
  {
    id: "horatio-alger",
    name: "Horatio Alger National Scholarship",
    provider: "Horatio Alger Association",
    scope: "national",
    group: "National",
    award: "$25,000 (about 106 national awards, plus state awards)",
    minGPA: 2.0,
    levels: ["incoming-freshman"],
    colleges: ["any"],
    needBased: true,
    meritBased: false,
    internationalEligible: false,
    tags: ["service"],
    deadline: { month: 3, day: 1 },
    deadlineNote: "Apply as a high school junior (window runs December to March 1). Seniors have a separate mid-February window.",
    sourceType: "official",
    stacking: "Outside award; stacks with university aid but can reduce need-based grants.",
    url: "https://scholars.horatioalger.org/scholarships/",
    requirements: [
      "For students who have overcome significant adversity.",
      "Demonstrated financial need (family income of $100,000 or lower).",
      "Involvement in co-curricular and service activities; 2.0+ GPA; U.S. citizen.",
    ],
  },
  {
    id: "gates-scholarship",
    name: "The Gates Scholarship",
    provider: "Bill & Melinda Gates Foundation",
    scope: "national",
    group: "National",
    award: "Full cost of attendance not covered by other aid (about 300 awards)",
    minGPA: 3.3,
    levels: ["incoming-freshman"],
    colleges: ["any"],
    needBased: true,
    meritBased: true,
    minorityOnly: true,
    internationalEligible: false,
    tags: ["leadership", "service"],
    deadline: { month: 9, day: 15 },
    deadlineNote: "Opens mid July, closes mid September, the fall before college.",
    sourceType: "official",
    stacking: "Last-dollar award: it fills whatever your other aid doesn't cover, so it layers on top of everything else.",
    url: "https://www.thegatesscholarship.org/scholarship",
    requirements: [
      "High school senior; Pell-eligible; U.S. citizen or permanent resident.",
      "From an ethnic background underrepresented in higher education.",
      "3.3+ weighted GPA; top 10% of class strongly preferred.",
    ],
  },
  {
    id: "jkc-transfer",
    name: "Jack Kent Cooke Undergraduate Transfer Scholarship",
    provider: "Jack Kent Cooke Foundation",
    scope: "national",
    group: "National",
    award: "Up to $55,000 per year (about 65 awards)",
    minGPA: 3.5,
    levels: ["transfer"],
    colleges: ["any"],
    needBased: true,
    meritBased: true,
    internationalEligible: false,
    tags: ["leadership"],
    deadline: { month: 1, day: 7 },
    deadlineNote: "Opens in August, closes in early January. For community college students transferring to a four-year school.",
    sourceType: "official",
    stacking: "Last-dollar funding after institutional aid, so it fills the remaining gap.",
    url: "https://www.jkcf.org/our-scholarships/undergraduate-transfer-scholarship/",
    requirements: [
      "Current community/two-year college student planning to transfer.",
      "3.5+ GPA and demonstrated unmet financial need.",
      "Covers tuition, living expenses, books, and fees for 2 to 3 years.",
    ],
  },
  {
    id: "dream-award",
    name: "Scholarship America Dream Award",
    provider: "Scholarship America",
    scope: "national",
    group: "National",
    award: "$5,000 to $15,000 per year, renewable and growing each year",
    minGPA: 3.0,
    levels: ["sophomore", "junior", "senior", "transfer"],
    colleges: ["any"],
    needBased: true,
    meritBased: true,
    internationalEligible: false,
    tags: [],
    deadline: { month: 3, day: 28 },
    deadlineNote: "Recent cycles closed in late March. One of the few big national awards for students already in college.",
    sourceType: "official",
    stacking: "Outside renewable award; the amount grows $1,000 each year and stacks with university aid.",
    url: "https://scholarshipamerica.org/scholarship/dreamaward/",
    requirements: [
      "Completed at least one full year of undergraduate study.",
      "3.0+ GPA and demonstrated financial need.",
      "U.S. citizen, permanent resident, or DACA.",
    ],
  },

  /* ================= National: talent-based ================= */
  {
    id: "goldwater",
    name: "Barry Goldwater Scholarship",
    provider: "Goldwater Foundation",
    scope: "national",
    group: "National",
    award: "Up to $7,500 per year (about 450 awards)",
    minGPA: 3.7,
    levels: ["sophomore", "junior"],
    colleges: ["any"],
    needBased: false,
    meritBased: true,
    internationalEligible: false,
    tags: ["stem"],
    requiredTags: ["stem"],
    deadline: { month: 1, day: 29 },
    deadlineNote: "Requires campus nomination, and BYU's internal deadline is months earlier. Start in the fall.",
    sourceType: "official",
    stacking: "Prestige award; stacks with university aid up to cost of attendance.",
    url: "https://goldwaterscholarship.gov/",
    requirements: [
      "Sophomore or junior in science, engineering, or math.",
      "Strong research experience and intent to pursue a research career.",
      "Must be nominated by your school's Goldwater representative.",
    ],
  },
  {
    id: "truman",
    name: "Harry S. Truman Scholarship",
    provider: "Truman Scholarship Foundation",
    scope: "national",
    group: "National",
    award: "Up to $30,000 for graduate school",
    minGPA: 3.5,
    levels: ["junior"],
    colleges: ["any"],
    needBased: false,
    meritBased: true,
    internationalEligible: false,
    tags: ["public-service", "leadership", "service"],
    requiredTags: ["public-service", "leadership", "service"],
    deadline: { month: 2, day: 3 },
    deadlineNote: "Foundation deadline in early February; campus nomination deadlines come months earlier.",
    sourceType: "official",
    stacking: "Funds graduate school, so it doesn't compete with your undergraduate aid at all.",
    url: "https://www.truman.gov/",
    requirements: [
      "College junior committed to a career in government or public service.",
      "Extensive record of public and community service.",
      "Must be nominated by your institution.",
    ],
  },
  {
    id: "udall",
    name: "Udall Undergraduate Scholarship",
    provider: "Udall Foundation",
    scope: "national",
    group: "National",
    award: "$7,500 (up to 65 awards)",
    minGPA: 3.0,
    levels: ["sophomore", "junior"],
    colleges: ["any"],
    needBased: false,
    meritBased: true,
    internationalEligible: false,
    tags: ["environment", "public-service"],
    requiredTags: ["environment"],
    deadline: { month: 3, day: 4 },
    deadlineNote: "Early March foundation deadline; campus internal deadlines can be up to six months earlier.",
    sourceType: "official",
    stacking: "Stacks with university aid up to cost of attendance.",
    url: "https://www.udall.gov/OurPrograms/Scholarship/Scholarship.aspx",
    requirements: [
      "Sophomore or junior committed to a career related to the environment (or tribal policy / Native health).",
      "Access to the application comes through your school's faculty representative.",
    ],
  },
  {
    id: "foot-locker",
    name: "Foot Locker Scholar Athletes Program",
    provider: "Foot Locker Foundation",
    scope: "national",
    group: "National",
    award: "$20,000 (20 awards)",
    minGPA: 3.0,
    levels: ["incoming-freshman"],
    colleges: ["any"],
    needBased: false,
    meritBased: true,
    talentBased: true,
    internationalEligible: false,
    tags: ["athletics", "leadership"],
    requiredTags: ["athletics"],
    deadline: null,
    deadlineNote: "Application window varies by year (recent cycles have closed in winter or spring). Verify on the official page.",
    sourceType: "secondary",
    stacking: "Outside award; stacks with university aid but must be reported.",
    url: "https://www.footlockerscholarathletes.com/",
    requirements: [
      "High school senior involved in sports at any level: school, intramural, or community.",
      "Not about being a star recruit. It rewards leadership through sport.",
      "3.0+ GPA; U.S. citizen or permanent resident.",
    ],
  },
  {
    id: "youngarts",
    name: "YoungArts National Arts Competition",
    provider: "National YoungArts Foundation",
    scope: "national",
    group: "National",
    award: "$250 to $10,000 plus mentorship and program access",
    minGPA: 0,
    levels: ["incoming-freshman"],
    colleges: ["any"],
    needBased: false,
    meritBased: false,
    talentBased: true,
    internationalEligible: true,
    tags: ["arts", "writing"],
    requiredTags: ["arts", "writing"],
    deadline: { month: 10, day: 8 },
    deadlineNote: "For ages 15 to 18 (grades 10 to 12). Applications close in early October.",
    sourceType: "official",
    stacking: "Cash award with no strings on other aid; winners also join a lifelong artist network.",
    url: "https://youngarts.org/apply/",
    requirements: [
      "Ages 15 to 18 or grades 10 to 12 on December 1 of the application year.",
      "Ten disciplines including dance, music, theater, visual arts, film, and writing.",
      "Judged entirely on your submitted work or audition.",
    ],
  },
  {
    id: "scholastic-awards",
    name: "Scholastic Art & Writing Awards (Portfolio Scholarships)",
    provider: "Alliance for Young Artists & Writers",
    scope: "national",
    group: "National",
    award: "Up to $12,500 (Gold Medal Portfolio) plus smaller sponsored awards",
    minGPA: 0,
    levels: ["incoming-freshman"],
    colleges: ["any"],
    needBased: false,
    meritBased: false,
    talentBased: true,
    internationalEligible: true,
    tags: ["arts", "writing"],
    requiredTags: ["arts", "writing"],
    deadline: { month: 12, day: 15 },
    deadlineNote: "Regional deadlines run December to early January and vary by region. Fee waivers available.",
    sourceType: "official",
    stacking: "Cash scholarship paid directly; no effect on university aid in most cases.",
    url: "https://www.artandwriting.org/",
    requirements: [
      "Grades 7 to 12; graduating seniors can submit a full portfolio for the top awards.",
      "Judged blind on originality, skill, and personal voice.",
      "Entry fees are small and waivable.",
    ],
  },
  {
    id: "hsf",
    name: "Hispanic Scholarship Fund Scholar Program",
    provider: "Hispanic Scholarship Fund",
    scope: "national",
    group: "National",
    award: "$500 to $5,000 (thousands of awards yearly)",
    minGPA: 2.5,
    levels: ["incoming-freshman", ...CONTINUING],
    colleges: ["any"],
    needBased: true,
    meritBased: true,
    minorityOnly: true,
    internationalEligible: false,
    tags: [],
    deadline: { month: 3, day: 31 },
    deadlineNote: "Recent cycles closed in late winter or spring; the exact window shifts, so verify on hsf.net.",
    sourceType: "secondary",
    stacking: "Stacks with university aid; HSF Scholars also get mentorship and career support.",
    url: "https://www.hsf.net/scholarship",
    requirements: [
      "Of Hispanic heritage; U.S. citizen, permanent resident, DACA, or eligible non-citizen.",
      "3.0+ GPA in high school, or 2.5+ GPA in college.",
      "Open to high school seniors AND current college students.",
    ],
  },
];
